export const GET_ARTIST_LIST = "GET_ARTIST_LIST";
export const GET_GENRES_LIST = "GET_GENRES_LIST";
export const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";